---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user:
    ansible_password:
    ANSIBLE_HOST_KEY_CHECKING: False
prod:
  hosts:
    client:
      ansible_host: 192.168.40.65
